### PR TITLE
better way to define c14_date_list as a subclass of tibble

### PR DESCRIPTION
**Pull request by nevrome**
This small change should make it possible to apply tidyverse functions like `dplyr::filter`, `dplyr::mutate` or `dplyr::select` without loosing the subclass `c14_date_list`. Much more convenient.

Please test and compare the master branch with this branch.

```
x <- get_aDRAC()
shu <- x %>% dplyr::mutate(nonsense = lat + lon)
class(shu)
```

If this works, we should do the same for mortAAR, @nmueller18.

### CODE REVIEW

**Comment by nmueller18** [comment]
To be honest, I do not really understand what you have done and what for but at least the code snippet you have posted seems to work (retain class `c14_date_list`). To implement this in mortAAR one would change this line:

> `class<-`(c("mortaar_life_table_list", class(.))) %>%

to something like that:

> tibble::new_tibble(., nrow = nrow(.), class = "mortaar_life_table_list") %>%

Correct? (still do not know why this might be useful)

**Comment by nevrome** [comment]
Please consider the following filter operation:

```
x <- get_aDRAC()
x %>% dplyr::filter(site == "Mbaere")
```

Let's take a look at the result without the change in this PR:

image

What we get is a normal data.frame print output.

Now the result with the change: 

image

The much more nice `c14_date_list` print output!

With this new way of `tibble` initialization we make sure that the subclass `c14_date_list`, which inherits from tibble, is not stripped from the table if we apply tidyverse operations to it. This is a very important change, because all functions in c14bazAAR require an object of class `c14_date_list` as input. They will not work without this subclass. In the past it was necessary to add the class again manually after the application of tidyverse functions.

You can change mortAAR like this as well with the code you presented. Most probably there are also other points in the package, where the subclasses `mortaar_life_table` or `mortaar_life_table_list` are added again, exactly because of this problem. These conversions can be removed [as well](https://github.com/ISAAKiel/c14bazAAR/pull/67/commits/16c9b0b202077936226d3ef4081175a1f5e5acbc).

**Comment by nevrome** [comment]
Btw. @nmueller18 I would like to add you to the DESCRIPTION of the package as a [contributor](https://journal.r-project.org/archive/2012-1/RJournal_2012-1_Hornik~et~al.pdf). Is this ok for you?

**Comment by nmueller18** [comment]
If you deem it justified, I have no objections.

**Comment by nmueller18** [comment]
> With this new way of tibble initialization we make sure that the subclass c14_date_list, which inherits from tibble, is not stripped from the table if we apply tidyverse operations to it. This is a very important change, because all functions in c14bazAAR require an object of class c14_date_list as input. They will not work without this subclass. In the past it was necessary to add the class again manually after the application of tidyverse functions.

Okay, now I see your point. I still have not got the hang of the tidy-universe ...

**Pull request merged**
