### PR TITLE
Standardize country name

### PR DESCRIPTION
**Pull request by nevrome**
OK - it somehow works. But I get the feeling it makes things worse instead of better.

### CODE REVIEW

**Comment by nevrome** [comment]
[Concerning the countrycode dependency problem...](https://github.com/vincentarelbundock/countrycode/issues/173)

**Comment by dakni** [comment]
Since there was only a  manual solution before I think the situation could not have getting worse, so it's fine. ;)

I try to check it more in detail on Friday. The code looks fine, however at the moment it does not work for me:

```r
> a <- c14bazAAR::get_aDRAC()
> standardize_country_name.c14_date_list(x = a, codesets = "iso3c")
Error in mutate_impl(.data, dots) : 
  Evaluation error: 'codelist' is not an exported object from 'namespace:countrycode'.
```

Is it due to a change in the code of the `countrycode` package? (I installed in from CRAN.) There is no function `codelist` [well, as the error explains it is not exported]...

**Comment by nevrome** [comment]
Thanks for testing!

The countrycode package developers changed the name of the actual code list data object since the last CRAN release. You have to install from github.  [Here](https://github.com/vincentarelbundock/countrycode/issues/173)'s the relevant issue once more.

**Comment by dakni** [comment]
thanks, that solved the problem (and now I also understood the issue -- I thought it was the other way around. nevermind.)

this call gives me a nice `country_thes` column

```r
standardize_country_name(c14bazAAR::get_aDRAC())
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 05s
	Radiocarbon date list
	dates		1258
	sites		478
	countries	12
	uncalBP		46500 ― 0 

# A tibble: 1,258 x 13
   sourcedb labnr    c14age c14std c13val site   feature material country
   <chr>    <chr>     <int>  <int>  <dbl> <chr>  <chr>   <chr>    <chr>  
 1 aDRAC    AA-78447   2362     39      0 Mbaere NA      NA       CAF    
 2 aDRAC    AA-78448   2171     37      0 Mbaere NA      NA       CAF    
 3 aDRAC    AA-78449    834     35      0 Mbaere NA      NA       CAF    
 4 aDRAC    AA-94529    215     34      0 Ngotto BB01-29 NA       CAF    
 5 aDRAC    AA-94530    168     35      0 Ngotto BB01-30 NA       CAF    
 6 aDRAC    AA-94531    207     35      0 Ngotto BB01-31 NA       CAF    
 7 aDRAC    AA-94532    148     34      0 Ngotto BB01-36 NA       CAF    
 8 aDRAC    AA-94533    231     34      0 Ngotto BB05-32 NA       CAF    
 9 aDRAC    AA-94534    187     34      0 Ngotto BB05-41 NA       CAF    
10 aDRAC    AA-94537    160     35      0 Ngotto ND01-03 NA       CAF    
# ... with 1,248 more rows, and 4 more variables: country_thes <chr>,
#   lat <dbl>, lon <dbl>, shortref <chr>

> head(standardize_country_name(c14bazAAR::get_aDRAC())$country_thes, 10)
   |++++++++++++++++++++++++++++++++++++++++++++++++++| 100% elapsed = 05s
                       CAF                        CAF 
"Central African Republic" "Central African Republic" 
                       CAF                        CAF 
"Central African Republic" "Central African Republic" 
                       CAF                        CAF 
"Central African Republic" "Central African Republic" 
                       CAF                        CAF 
"Central African Republic" "Central African Republic" 
                       CAF                        CAF 
"Central African Republic" "Central African Republic" 

```


## something else 1: 
`magrittr` seems not be properly imported since without loading it manually I get the following error

```r
b <- standardize_country_name(a)
Error in x %<>% add_or_replace_column_in_df("country_thes", NA, .after = "country") (from unknown!8194GgX#7) : 
  could not find function "%<>%
```

## something else 2: 
although I rebuild the package locally, I have to manually execute the functions `check_if_packages_are_available` and `add_or_replace_column_in_df`as they seem not to be exported yet.

**Comment by nevrome** [comment]
Yes aDRAC is the only database where the code is unconditionally useful. 
For the other databases we get a lot of false corrections unfortunately: Scotland becomes Iceland, because Scotland is not a country. Israel/Palestine becomes Palestine, because Palestine is a longer word than Israel and therefore the text distance sum is smaller with Palestine. That's why I agree now that we should skip this and only extract country information from coordinates -- except maybe for those databases where no coordinates are supplied (14SEA).

I can't reproduce the bugs **something else 1** and **something else 1**. `%<>%` clearly is imported in the namespace and it should not be necessary to export the helper functions. Could you please try to install the package via devtools and test it again?
```
devtools::install_github("ISAAKiel/c14bazAAR", ref = "standardize_country_name")
```

**Comment by dakni** [comment]
installing via `devtools` resolved the issue -- i was on the wrong branch *grrr*

**Comment by nevrome** [comment]
Applied to all databases the algorithm makes the following decisions:

> AGO -> Angola
> Andora -> Andorra
> BDI -> Burundi
> Bosnia and Herzegovina -> Bosnia & Herzegovina
> CAF -> Central African Republic
> Channel Isles -> Channel Islands
> CMR -> Cameroon
> COD -> Congo - Kinshasa
> COG -> Congo - Brazzaville
> Corsica -> China
> Crete -> Chile
> Czech Republic -> Czechoslovakia
> Egypt_Sinai -> Egypt
> England/Wales -> Bangladesh
> former Yugoslavia -> Yugoslavia
> GAB -> Gabon
> GHA -> Ghana
> GNQ -> Equatorial Guinea
> Great Britain -> Bahrain
> Irak -> Iraq
> Israel, Palestine -> Palestinian Territories
> Israel/Palestina -> Palestinian Territories
> Israel/West Bank/Gaza Strip -> Western Sahara
> Libanon -> Lebanon
> Mallorca -> Malaysia
> Moldavia -> Moldova
> probably Ireland? -> Marshall Islands
> Russian Federation -> Russia
> RWA -> Rwanda
> Sardinia -> Armenia
> Scotland -> Iceland
> Serbia and Montenegro -> Montenegro
> SFRY -> Faroe Islands
> TCD -> Chad
> Turkmenia -> Armenia
> U.A.E. -> Azerbaijan 

Some are useful, some are bullshit. I'm pretty sure that we need a manually curated list for the most ridiculous  stuff. I think we can solve this with a getter function like `get_db_url()` and a csv file in this repo.

**Pull request merged**
