### PR TITLE
get_EUBAR()

### PR DESCRIPTION
**Pull request by dirkseidensticker**
A testing candidate for a get_EUBAR parser; see #2 .

In order to work correctly from the branch I have set [`ref_url <-`](https://github.com/ISAAKiel/c14bazAAR/blob/EUBAR/R/helpers_db_urls.R#L13) to use the EUBAR branch instead of master. **This need to be removed before merging.**

Please test and comment

### CODE REVIEW

**Comment by nevrome** [comment]
Looks good at first glance. Thank you!

Maybe you could also update the [variable_reference table](https://github.com/ISAAKiel/c14bazAAR/blob/master/data-raw/variable_reference.csv). And maybe the [material_thesaurus comments](https://github.com/ISAAKiel/c14bazAAR/blob/master/data-raw/material_thesaurus_comments.md). 

The country table does not need an update with this database, ja?

**Comment by dirkseidensticker** [comment]
I have updated the county table as well as variable reference and material thesaurus comments. Before merge please be aware that [helpers_db_urls.R#L13](https://github.com/ISAAKiel/c14bazAAR/blob/EUBAR/R/helpers_db_urls.R#L13) needs to be removed and [helpers_db_urls.R#L11](https://github.com/ISAAKiel/c14bazAAR/blob/EUBAR/R/helpers_db_urls.R#L12) uncommented

**Comment by nevrome** [comment]
Based on your experience with this getter: Is the checklist [here](https://github.com/ISAAKiel/c14bazAAR#adding-database-getter-functions) complete?

**Comment by dirkseidensticker** [comment]
Yeah I think the checklist is comprehensive enough. I have updated the NEWS.md and reset the ref_url back to the master branch. Are you okay with merging?

**Comment by dirkseidensticker** [comment]
Oh, I only saw now now that you already updated the NEWS.md, which creates a conflict. I can resolve this and merge once you are okay

**Comment by nevrome** [comment]
Excellent, Dirk!

**Pull request merged**
