### PR TITLE
Preference selection duplicates

### PR DESCRIPTION
**Pull request by nevrome**
#62

### CODE REVIEW

**Comment by nmueller18** [comment]
The new preference-selection seem to work as expected! In the documentation, I would highlight this feature because otherwise users will wondering why so many dates are missing.

I got an error message concerning one of the databases and a problem with the function `classify_material`. Here is the message:

> Fehler in curl::curl_download(input, tmpFile <- tempfile(), mode = "wb",  : 
>  Timeout was reached: Resolving timed out after 10000 milliseconds 
>43.
>curl::curl_download(input, tmpFile <- tempfile(), mode = "wb", 
>    quiet = !showProgress) 
>42.
>data.table::fread(url, colClasses = c(cor = "character", var = "character"), 
>    showProgress = FALSE) 
>41.
>eval(lhs, parent, parent) 
>40.
>eval(lhs, parent, parent) 
>39.
>data.table::fread(url, colClasses = c(cor = "character", var = "character"), 
>    showProgress = FALSE) %>% tibble::as.tibble() at helpers_thesauri.R#33
>38.
>get_thesaurus(.) 
>37.
>function_list[[i]](value) 
>36.
>freduce(value, `_function_list`) 
>35.
>`_fseq`(`_lhs`) 
>34.
>eval(quote(`_fseq`(`_lhs`)), env, env) 
>33.
>eval(quote(`_fseq`(`_lhs`)), env, env) 
>32.
>withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
>31.
>"https://raw.githubusercontent.com/ISAAKiel/c14bazAAR/master/data-raw/material_thesaurus.csv" %>% 
>    get_thesaurus() %>% return() at helpers_thesauri.R#18
>30.
>c14bazAAR::get_material_thesaurus() 
>29.
>x %in% thesaurus_df$var 
>28.
>ifelse(x %in% thesaurus_df$var, thesaurus_df$cor[match(x, thesaurus_df$var)], 
>    x) 
>27.
>eval(lhs, parent, parent) 
>26.
>eval(lhs, parent, parent) 
>25.
>ifelse(x %in% thesaurus_df$var, thesaurus_df$cor[match(x, thesaurus_df$var)], 
>    x) %>% return() at c14_date_list_classify_material.R#83
>24.
>lookup_in_thesaurus_table(.$material, material_thesaurus) 
>23.
>mutate_impl(.data, dots, caller_env()) 
>22.
>mutate.tbl_df(tbl_df(.data), ...) 
>21.
>mutate(tbl_df(.data), ...) 
>20.
>as.data.frame(mutate(tbl_df(.data), ...)) 
>19.
>mutate.data.frame(., material_thes = lookup_in_thesaurus_table(.$material, 
>    material_thesaurus)) 
>18.
>dplyr::mutate(., material_thes = lookup_in_thesaurus_table(.$material, 
>    material_thesaurus)) 
>17.
>function_list[[i]](value) 
>16.
>freduce(value, `_function_list`) 
>15.
>`_fseq`(`_lhs`) 
>14.
>eval(quote(`_fseq`(`_lhs`)), env, env) 
>13.
>eval(quote(`_fseq`(`_lhs`)), env, env) 
>12.
>withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
>11.
>x %<>% dplyr::mutate(material_thes = lookup_in_thesaurus_table(.$material, 
>    material_thesaurus)) %>% as.c14_date_list() at c14_date_list_classify_material.R#61
>10.
>classify_material.c14_date_list(.) at c14_date_list_classify_material.R#34
>9.
>classify_material(.) 
>8.
>function_list[[k]](value) 
>7.
>withVisible(function_list[[k]](value)) 
>6.
>freduce(value, `_function_list`) 
>5.
>`_fseq`(`_lhs`) 
>4.
>eval(quote(`_fseq`(`_lhs`)), env, env) 
>3.
>eval(quote(`_fseq`(`_lhs`)), env, env) 
>2.
>withVisible(eval(quote(`_fseq`(`_lhs`)), env, env)) 
>1.
>x %>% classify_material() 
>

**Comment by nevrome** [comment]
Thanks for testing. How would you highlight this feature beyond the description that's already there?

I can't reproduce your error here. Is it possible, that your internet connection was not stable at this moment? A curl timeout is usually a sign of internet connection issues.

**Comment by nmueller18** [comment]
Re highlighting: Perhaps even make the preference-list the default?

Re error: You might be right. I also cannot reproduce the error with `classify_material` at the moment.

**Comment by nevrome** [comment]
I'm very hesitant to do this. I would have to define a default preference list and I don't want to do that. Maybe we could add a warning message for the user when he does not provide a preference vector?

**Comment by nmueller18** [comment]
I understand. A warning is perhaps a better and more satisfying solution. There, the user could be confronted with the ensuing horrors of innumerable NAs in his resulting data table!  ;-)

**Comment by nevrome** [comment]
I added a message now. 

@dirkseidensticker Do you have a moment to also test this new preferences feature in `remove_duplicates`?
You can install the version from this branch directly with `devtools::install_github("ISAAKiel/c14bazAAR#63")`

**Comment by dirkseidensticker** [comment]
@nevrome your addition of the `preference` option works as expected besides a minor issue I encountered. I used the example that @nmueller18 provided in #62 :

```
x <- get_all_dates()
x_material <- x %>% classify_material()
x_country <- x_material %>%
  standardize_country_name() %>%
  determine_country_by_coordinate() %>%
  finalize_country_name()
x_duplicate <- x_country %>%
  mark_duplicates() %>%
  remove_duplicates()
```

`remove_duplicates()` (the default) would still remove all dates from Viesenhäuser Hof, as
```
View(x_duplicate[grepl("Viesen", x_duplicate$site),])
```
produces no results. But:
```
View(x_country[grepl("Viesen", x_country$site),])
```
shows 60 entries from CALPAL, EUROEVOL and RADON. I think thus far we are all on the same page.

---

Now with the preferences set as you suggested
```
x_duplicate2 <- x_country %>%
  mark_duplicates() %>%
  remove_duplicates(preferences = c("RADON", "CALPAL", log = TRUE))
View(x_duplicate2[grepl("Viesen", x_duplicate2$site),])
```
we get the 20 dates we wanted. **But** when I look into the `log` column (e.g. `x_duplicate2$duplicate_remove_log[24982]` for date Hd-8099) I see data from the 14SEA database as well:
```
[1] "sourcedb: 14SEA|CALPAL, method: NA|14C, labnr: MAMS-15270, c14age: 7883, c14std: 34, c13val: -25.2, site: Çukuriçi Höyük|Cukurici, sitetype: NA, feature: 11/1398/11/1|NA, period: EN|Neolithic, culture: NA|LN, material: Grain|grain, material_thes: plant remains, species: NA, region: Eastern Aegean|NA, country: Turkey, country_coord: NA|Turkey, country_thes: Turkey, country_final: Turkey, lat: NA|37.931, lon: NA|27.352, shortref: Weninger et al. 2014|Kromer 24.07.2012, comment: NA, duplicate_group: 479"
```

Is that a bug on my side? I have not been able to debug the code that generate the log string thus far, but I hope to do that soon.

If I am now a really stupid user and supply a database with less information, like 14SEA I get weird output again:
```
x_duplicate3 <- x_country %>%
  mark_duplicates() %>%
  remove_duplicates(preferences = c("14SEA", log = TRUE))

View(x_duplicate3[grepl("Viesen", x_duplicate3$site),])
```
In this example the field `feature` and `sitetype` (among others I guess) are `NA` again, but `period` is filled with 'Neolithic' out of a sudden. This info comes from CALPAL but has been overwritten earlier because RADON misses the `period` entry and was set as most trustworthy. I know it is a big problem and I am unable to provide a quick fix as well. Sorry for pocking around as well.

But I would like to suggest to drop the default at all as it seem to only generate problems. One fast suggestion: could we rate the 'quality' of the databases and provide a default? A very rudimentary first try
```
x_country$na_count <- rowSums(is.na(x_country))
x_db <- aggregate(x_country$na_count, by=list(x_country$sourcedb), FUN=mean)
x_db <- x_db[order(x_db$x),]
pref <- c(x_db[1:2,"Group.1"])
```
that simply counts how many `NA`s are within each row and based on the mean per database the two *best* (lowest mean-NA) databases can be used as the default unless the user provides his choice. Personally I am of course disappointed that aDRAC has the second highest mean-NA; but that's life. And please excuse that my code is in no way tidy, I still can't get my head around it 🙈

@nevrome & @nmueller18 what do you think of that and can you reproduce my problem with the log-output?

**Comment by dirkseidensticker** [comment]
@nevrome as you pointed out I put the `log = TRUE` inside the `preference = c()`, which is incorrect. I corrected that, but still got the same output (stuff from other db's in the log string etc). My full testing script:

```r
x <- get_all_dates()
x_material <- x %>% classify_material()
x_country <- x_material %>%
  standardize_country_name() %>%
  determine_country_by_coordinate() %>%
  finalize_country_name()
x_duplicate <- x_country %>%
  mark_duplicates() %>%
  remove_duplicates()
View(x_duplicate[grepl("Viesen", x_duplicate$site),])
# turns out empty

View(x_country[grepl("Viesen", x_country$site),])
# shows 60 entries from CALPAL, EUROEVOL and RADON

x_duplicate2 <- x_country %>%
  mark_duplicates() %>%
  remove_duplicates(preferences = c("RADON", "CALPAL"), log = TRUE)
View(x_duplicate2[grepl("Viesen", x_duplicate2$site),])
# log contains information from some other dates inside 14SEA

x_duplicate3 <- x_country %>%
  mark_duplicates() %>%
  remove_duplicates(preferences = c("14SEA"), log = TRUE)
View(x_duplicate3[grepl("Viesen", x_duplicate3$site),])
# giving the 'wrong' source database results in weird output again; in this case the features got dropped & period added

# default db's testing:
# ----------------------
x_country$na_count <- rowSums(is.na(x_country))
x_db <- aggregate(x_country$na_count, by=list(x_country$sourcedb), FUN=mean)
x_db <- x_db[order(x_db$x),]
pref <- c(x_db[1:2,"Group.1"])
```

@nevrome & @nmueller18  please test and comment

**Comment by nevrome** [comment]
@dirkseidensticker 

Thank you very much for this thorough test! Excellent! That's what ISAAK is about!

I'm pretty sure, that your test results are actually expected behaviour. That might seem weird to you, but let me explain. The confusion on your site is the best proof that the current expected behaviour is not good and we have to agree on a better solution.

The crucial question is, how the preference order is defined **beyond** the user selection. The user supplies his preferred order of databases and this order can be applied for all the overlapping dates which appear in these databases. But what about the other dates? We need to define an order beyond the user selection, if we do not want to force the user to provide a complete rank table with all databases.

Please take a look at this line of code in `c14_date_list_duplicates_remove.R` that describes my current solution:

```
 preference_based_order <- unique(c(preferences, duplicates$sourcedb %>% unique))
```

The user supplied order vector `preferences` is **extended** by a list of unique databases in the input data selection. In this case the order of this extension depends on the order established in `get_all_dates()` and is therefore arbitrary. 

***

What other ways of solving this do we have? Some ideas:

1. Establishing a default order of databases based on our subjective judgement.

2. Establishing a default order of databases based on a criterion like e.g. the one suggested by Dirk: Total number of missing values.

3. If the user provides a preferences vector, then all dates which can not be found in the supplied databases are removed.

***

I will not allow **1.** unless you have some really strong arguments to support a consistent order of all current and future databases. **2.** would be ok for me, although I do think this solution is too *technical*. It just ignores the differences in relevance of databases and variables for different research questions. That leaves me with **3.**. I like this solution. It's simple for me/us. Would also solve the "problem" of unexpected values in the log column. But is it a good solution?

What do you think @dirkseidensticker and @nmueller18? Whatever we decide: We have to document it well.

**Comment by nmueller18** [comment]
I think neither of the solutions is truely satisfying. The big strength of c14bazAAR is the ability to gather c14-dates with a shotgun-approach, without too much consideration of the origin of the data. With solution no. 3, the user has to be familiar with the databases to choose the appropriate ones, and she/he could still miss relevant entries. 

What about populating the cells of rows present in more than one database with ALL entries (if they differ)? This defies the thesaurus-approach a bit, but the chances would increase that a subsetting would find more relevant dates. The user had to be made aware, of course, that the subsets MUST then work with wildcards.
As a further step, one could use this information to build a concordance list on, say, cultures or periods (for example, you would probably discover that "Linearbandkeramik" is the same as "Culture rubanée" and that it is a Neolithic culture). Indeed, you could see this as a increase in information density which in the overwhelming number of cases will heighten the value of the result for the user.

**Comment by nmueller18** [comment]
The more I think about it, the more I like this idea. You could even present the user with a Cluster map to show which terms are related ...

**Comment by nevrome** [comment]
@nmueller18 Thank you for the fast feedback.

We have to keep in mind, that the true default is still `preferences = NULL` exactly because of this problem. With this solution the user gets every date, but with all uncertain (aka inconsistent) information removed. 

I do not like your solution. In my opinion this is a technical nightmare with several bad consequences. The important data type definitions established in c14bazAAR (e.g. coordinates are stored as doubles) would be completely dissolved and the usability of the dataset therefore greatly reduced. The resulting table could not be a `c14_date_list` any more. All features provided by c14bazAAR would then be unusable and all other data analysis beyond the realms of the package greatly hampered. The resulting data structure would not be tidy by any means. 

**But**: Your idea for concordance list analysis is great! Could yield some great results. It does not solve this problem though.

What about a compromise: `preferences` behaves as described in `3.`, but we provide one or multiple simple helper functions that allow the user to select predefined orders (based on **2.**).

**Comment by dirkseidensticker** [comment]
@nevrome & @nmueller18 I need to confess that I might need some more time to follow your ideas presented here. But I would like to go back to the initial problem, which was that a `NA` value in a more(?) preferred database can override a value present in another database, right? Thus the main question might not be how to present the user with the correct result, which we could not know in most cases, but with a result at all. If I am not mistaken, and I would like to invest some more time in order to understand what `remove_duplicates()` does in any cases, a value should always 'win' over a `NA`. If that happens the user has data to work with and needs to consult the log-string in order to find out how spread the values are.

@nevrome I need to debug https://github.com/ISAAKiel/c14bazAAR/blob/master/R/c14_date_list_duplicates_remove.R#L96 for this, right?

**Comment by nevrome** [comment]
> a value should always 'win' over a NA

In my humble opinion this is not true. If different databases deviate, then `NA` is a very **correct** way to represent the divergence. `compare_and_combine_data_frame_values()` works exactly as intended and needs no debugging. At least there is no issue that I'm aware of. 

**But:** We could discuss yet another approach to the problem. And I think that fits to your perception, @dirkseidensticker. When I understand you correctly, you want to go beyond the current approach of presenting the user with discrete datasets as they are provided by individual databases. Instead it seems that you want to combine datasets from different databases to create merged superdatasets. That would indeed require an additional function next to and like `compare_and_combine_data_frame_values()`.

This approach would be the best solution to gather the most knowledge about an individual date. Unfortunately it causes another problem down the road: Data citation issues. It becomes very difficult to pinpoint where values are coming from, if you combine information on the dataset level. In the future, individual datasets may/will even have DOIs.

Anyway: We could offer a function to do this, and you're very welcome to develop one! But probably that's something for a new PR after this one is merged.

**Comment by dirkseidensticker** [comment]
@nevrome  debugging was the wrong term. You are right the function does what it is suppose to do. Thus let's merge this PR and I think about a alternative  solution. But you are quite right in that if we have a comparison on the level of individual values correct attribution seems nearly impossible.

**Comment by nevrome** [comment]
@dirkseidensticker I added a first implementation of the **supermerge** option. Give it a try!

**Comment by nmueller18** [comment]
With the new version, the following line of code:

`x_duplicate <- x_country %>% mark_duplicates() %>%  remove_duplicates(preferences = c("RADON", "CALPAL", "EUROEVOL"), supermerge = TRUE)`

produces this error:

`Fehler in rbind(deparse.level, ...) : 
  numbers of columns of arguments do not match`

**Comment by nevrome** [comment]
Thank you very much, @nmueller18. Should be fixed now. 

Unfortunately this supermerge operation takes very long. I like the current implementation -- because it's elegant -- but I think I have to replace it to add a progress bar.

**Comment by nevrome** [comment]
I added progress bars now and fixed some other errors.

**Comment by dirkseidensticker** [comment]
I have tested the new `supermerge = TRUE` option and it worked perfectly 🎱
While it seems hard now to trance back the origin for an information, this function is great in order to get a extensive dataset. I would merge now and close this PR

**Comment by nevrome** [comment]
Excellent, @dirkseidensticker! Thank you very much for testing!

What do you say, @nmueller18?

**Comment by nmueller18** [comment]
@nevrome: I appreciate the time you put into solving the issue I raised, but to be honest, I am not fully convinced of the "supermerge"-functionality (see below). For one, however, it is definitely an improvement in merging the information in different databases. While `supermerge = FALSE` produces non-sensical information in the column `duplicates_remove_log` (e. g. for the Schletz-dates), the merged data seems correct with `supermerge = TRUE`. Whatever you have done differently, you should also implement the supermerge-algorithm for the `duplicates_remove_log`.

My main problem with the supermerge-functionality is that hardly anyone will use it. To make use of it, you would have to dissect the data again. While this may not seem too difficult, you would then have to join it with the data containing no duplicates. These are too many obstacles for the regular user.

That said, the function works as expected, and I agree that the branch can be merged.

**Comment by nevrome** [comment]
@nmueller18 Good spotting! Should be fixed now. 

I'm also not sure how useful this option actually is. But it does not hurt to have it.

**Pull request merged**
